//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquationApp.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EquationApp.Properties.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string btnCalculate {
            get {
                return ResourceManager.GetString("btnCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide How.
        /// </summary>
        public static string btnHideHow {
            get {
                return ResourceManager.GetString("btnHideHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Me How.
        /// </summary>
        public static string btnShowMeHow {
            get {
                return ResourceManager.GetString("btnShowMeHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string distance_SUAT_distanceAnswer {
            get {
                return ResourceManager.GetString("distance_SUAT_distanceAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a value to calculate.
        /// </summary>
        public static string emptyEquationPickerResult {
            get {
                return ResourceManager.GetString("emptyEquationPickerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value to calculate.
        /// </summary>
        public static string emtpyEquationPickerCalculate {
            get {
                return ResourceManager.GetString("emtpyEquationPickerCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot divide by 0.
        /// </summary>
        public static string errorDivideByZeroMessage {
            get {
                return ResourceManager.GetString("errorDivideByZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid number into the fields.
        /// </summary>
        public static string errorFormatMessage {
            get {
                return ResourceManager.GetString("errorFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquationApp is a project part of PaguCo
        ///
        ///All feedback is welcomed via the below link (Good or Bad).
        /// </summary>
        public static string lblAboutUs {
            get {
                return ResourceManager.GetString("lblAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} m/s^2.
        /// </summary>
        public static string lblResultAcceleration {
            get {
                return ResourceManager.GetString("lblResultAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} A.
        /// </summary>
        public static string lblResultCurrent {
            get {
                return ResourceManager.GetString("lblResultCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} m.
        /// </summary>
        public static string lblResultDistance {
            get {
                return ResourceManager.GetString("lblResultDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ohms.
        /// </summary>
        public static string lblResultResistance {
            get {
                return ResourceManager.GetString("lblResultResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} s.
        /// </summary>
        public static string lblResultTime {
            get {
                return ResourceManager.GetString("lblResultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} m/s.
        /// </summary>
        public static string lblResultVelocity {
            get {
                return ResourceManager.GetString("lblResultVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} V.
        /// </summary>
        public static string lblResultVoltage {
            get {
                return ResourceManager.GetString("lblResultVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration:.
        /// </summary>
        public static string lblTitleAcceleration {
            get {
                return ResourceManager.GetString("lblTitleAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to calculate:.
        /// </summary>
        public static string lblTitleCalculate {
            get {
                return ResourceManager.GetString("lblTitleCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current (I):.
        /// </summary>
        public static string lblTitleCurrent {
            get {
                return ResourceManager.GetString("lblTitleCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string lblTitleDistance {
            get {
                return ResourceManager.GetString("lblTitleDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Velocity:.
        /// </summary>
        public static string lblTitleFinalVelocity {
            get {
                return ResourceManager.GetString("lblTitleFinalVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Velocity:.
        /// </summary>
        public static string lblTitleInitialVelocity {
            get {
                return ResourceManager.GetString("lblTitleInitialVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance (R):.
        /// </summary>
        public static string lblTitleResistance {
            get {
                return ResourceManager.GetString("lblTitleResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string lblTitleTime {
            get {
                return ResourceManager.GetString("lblTitleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity:.
        /// </summary>
        public static string lblTitleVelocity {
            get {
                return ResourceManager.GetString("lblTitleVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage(V):.
        /// </summary>
        public static string lblTitleVoltage {
            get {
                return ResourceManager.GetString("lblTitleVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paguco.
        /// </summary>
        public static string paguco {
            get {
                return ResourceManager.GetString("paguco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a type.
        /// </summary>
        public static string pickerEquationTitle {
            get {
                return ResourceManager.GetString("pickerEquationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string pickerResultAcceleration {
            get {
                return ResourceManager.GetString("pickerResultAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string pickerResultDistance {
            get {
                return ResourceManager.GetString("pickerResultDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Velocity.
        /// </summary>
        public static string pickerResultFinalVelocity {
            get {
                return ResourceManager.GetString("pickerResultFinalVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Velocity.
        /// </summary>
        public static string pickerResultInitialVelocity {
            get {
                return ResourceManager.GetString("pickerResultInitialVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string pickerResultTime {
            get {
                return ResourceManager.GetString("pickerResultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string pickerResultVelocity {
            get {
                return ResourceManager.GetString("pickerResultVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current running through an element is equal to the voltage divided by the resistance.
        ///{0} = {1} / {2}.
        /// </summary>
        public static string resistance_RVI_currentAnswer {
            get {
                return ResourceManager.GetString("resistance_RVI_currentAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resistance across an element is equal to the voltage across the element divided by the current running through it.
        ///{0} = {1} / {2}.
        /// </summary>
        public static string resistance_RVI_resistanceAnswer {
            get {
                return ResourceManager.GetString("resistance_RVI_resistanceAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The voltage across an element it equal to resistance of that element multiplied by the amount of current running through.
        ///{0} = {1} * {2}.
        /// </summary>
        public static string resistance_RVI_voltageAnswer {
            get {
                return ResourceManager.GetString("resistance_RVI_voltageAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance travelled of and object is equal to the velocity of the object multiplied by the time it takes.
        /// {0} = {1} * {2}.
        /// </summary>
        public static string velocity_VDT_distanceAnswer {
            get {
                return ResourceManager.GetString("velocity_VDT_distanceAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time taken for an object to travel a distance is equal to the distance travelled divide by the velocity. 
        /// {0} = {1} / {2}.
        /// </summary>
        public static string velocity_VDT_timeAnswer {
            get {
                return ResourceManager.GetString("velocity_VDT_timeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Velocity of an object is equal to the distance travelled divided by the time taken.
        ///{0} = {1} / {2}.
        /// </summary>
        public static string velocity_VDT_velocityAnswer {
            get {
                return ResourceManager.GetString("velocity_VDT_velocityAnswer", resourceCulture);
            }
        }
    }
}
